### ISSUE TITLE
Criar o Wireframing das telas do app

### ISSUE THREAD

**Issue by dreyrobert** [practice-uffs/app-practice-react-native#18]
O objetivo dessa Issue é desenvolver um wireframing, ou seja um protótipo do design de interface do aplicativo, a fim de reconhecer a experiência que o usuário terá quando estiver utilizando este software, assim também conseguiremos montar um Design UX e UI para o app de forma mais efetiva.

**Comment by alissonpeloso** [comment]
Como está indo aqui? Se puder compartilhar o figma pra ir acompanhando, seria bacana.

**Comment by dreyrobert** [comment]
Experiência do usuário dentro do aplicativo concluída.
Projeto a partir do link: 
https://excalidraw.com/#json=HsHDo5QYCTehrE4LiHkKa,kTagjS9T7UJMXTf9wBeE6g

![Image](https://user-images.githubusercontent.com/99030697/196294502-01beb690-7543-4d79-b719-deac5845cb8f.png)
![Image](https://user-images.githubusercontent.com/99030697/196294503-f80d3f75-3728-4dc4-bd82-ff13b53b0637.png)
