### ISSUE TITLE
Continuidade do Design do App no Figma

### ISSUE THREAD

**Issue by dreyrobert** [practice-uffs/app-practice-react-native#31]
O objetivo desta issue é completar o Deisgn do aplicativo no figma, a partir da criação das seguintes telas:

- [x] Login Page
- [x] Início
- [ ] QR Code
- [ ] Aura
- [x] Perfil

Segue o projeto: https://www.figma.com/file/5yLrDoc4dDUc1b3uE94Zqd/Practice-UFFS-App-in-React?node-id=0%3A1

**Comment by dreyrobert** [comment]
Tela de Início:
![inicioapp](https://user-images.githubusercontent.com/99030697/196295529-0cbe71c8-912c-4e72-830f-3896adf07f43.png)
Tela de Login:
![loginpage](https://user-images.githubusercontent.com/99030697/196295534-f7bcee5d-f392-445f-a8a2-b1f749b0697d.png)
Tela de Perfil:
![perfil](https://user-images.githubusercontent.com/99030697/196295535-676699c3-438a-4ed1-9f07-b3be4e810863.png)

**Comment by zorteaadriano** [comment]
@dreyrobert coloquei alguns comentários no protótipo do figma, mas são só sugestões mesmo
